### ISSUE TITLE
sign_transaction throws binary exception: [Errno 8] Exec format error: '/app/kmstool_enclave_cli'

### ISSUE THREAD

**Issue by florianpreusner** [aws-samples/aws-nitro-enclave-blockchain-wallet#12]
* A reproducible test case or series of steps
  *  I followed the tutorial ([part 2](https://aws.amazon.com/blogs/database/part-2-aws-nitro-enclaves-for-secure-blockchain-key-management/)) and executed all steps on my apple silicon macbook (M2). I was able to set the key by lambda function using operation set_key: 
  ```
  {
    "operation": "set_key",
    "eth_key": "GENERATED_KEY_BY_FOLLOWING_OPENSSL_CMD_IN_TUTORIAL"
  }
  ```
So, I could successfully deploy the stack, run lambda function and setting up the right key policy. But when running following:
```
{
  "operation": "sign_transaction",
  "transaction_payload": {
    "value": 0.01,
    "to": "0xa5D3241A1591061F2a4bB69CA0215F66520E67cf",
    "nonce": 0,
    "type": 2,
    "chainId": 4,
    "gas": 100000,
    "maxFeePerGas": 100000000000,
    "maxPriorityFeePerGas": 3000000000
  }
}
```
I get following error: "exception happened calling kms binary: [Errno 8] Exec format error: '/app/kmstool_enclave_cli'"

* The version of our code being used
  * main branch (https://github.com/aws-samples/aws-nitro-enclave-blockchain-wallet/commit/ac0e56dacd78bcf320cf281c315a2a32a7e8f847)

* Any modifications you've made relevant to the bug
  * I had to upgrade toolchain version from 1.60 to 1.63, line 20 in Dockerfile.al2 that can be found in application/eth1/enclave/kms/aws-nitro-enclaves-sdk-c/containers which will be checked out by git clone in scripts/build_kmstool_enclave_cli.sh using version v0.3.1

* Anything unusual about your environment or deployment
  * N/A

I will try to run the tutorial also on an Intel based Mac the next days to see if it's working there. I will keep you posted.

_This issue has been moved from https://github.com/aws/aws-nitro-enclaves-sdk-c/issues/117_

**Comment by dpdornseifer** [comment]
Hi @florianpreusner thanks for opening the issue. Just pushed an update to automatically update the Rust toolchain and thus avoid the `kmstool_enclave_cli` build issue. The current build does not support cross-platform capabilities right now. 
Did you try an x86 platform like AWS Cloud9 as a build environment?

**Comment by KiranMo27** [comment]
Hey @dpdornseifer 
I am facing the same issue as @florianpreusner. I used the code on the latest main branch and am still continuing to run into the error. 

the exact error message is as follows:
`exception happened calling kms binary: [Errno 8] Exec format error: \\'/app/kmstool_enclave_cli`

Any pointers would be highly appreciated !

**Comment by florianpreusner** [comment]
I was running the tutorial successfully on intel based mac now by using newest main branch (https://github.com/aws-samples/aws-nitro-enclave-blockchain-wallet/commit/7f796d3a7c48c78b92540c00bc9e0ad01f51090e).
I didn't had to touch anything, no code changes have been required.

```
{
  "transaction_signed": "0x02f873048084b2d05e0085174876e800830186a094a5d3241a1591061f2a4bb69ca0215f66520e67cf872386f26fc1000080c001a03dd41959324fef6c7c6a7db01c4c5b30c086fdc165efc5e83375f26ec01149a3a04fcac1b271271f2fe20136f306747decb9eb19774b80729127712c1c84c942e6",
  "transaction_hash": "0x4b0b28980815fe677a81dd6f60c13e1d4bda230308499bd1e3f5176b88b06fc5"
}
```

**Comment by dpdornseifer** [comment]
Thanks for testing @florianpreusner . Also just added the target platform flag as pointed out [here]( https://github.com/aws/aws-nitro-enclaves-sdk-c/issues/117) by @richardfan1126 . 

@KiranMo27 the branch can be found [here](https://github.com/aws-samples/aws-nitro-enclave-blockchain-wallet/tree/feature/linux_amd64_target)

**Comment by KiranMo27** [comment]
Hey @dpdornseifer 
Thanks a ton for the pointer and the very quick fix. I tried out the solution in the above mentioned branch and it works perfectly. Thank you !!
