### ISSUE TITLE
Updating the code in the Enclave and the Server

### ISSUE THREAD

**Issue by KiranMo27** [aws-samples/aws-nitro-enclave-blockchain-wallet#14]
I would like to update the code that is running on the Nitro Enclave as well as the server ideally without deleting the currently deployed stack and redeploying it. Any pointers on how I can update the code would be highly appreciated!

The version of code being used
- main branch (https://github.com/aws-samples/aws-nitro-enclave-blockchain-wallet/commit/ac0e56dacd78bcf320cf281c315a2a32a7e8f847)

<br>

Any modifications you've made relevant to the bug
- N/A

<br>

Anything unusual about your environment or deployment
- N/A

**Comment by dpdornseifer** [comment]
Hi @KiranMo27 , 

if you are using the reference code you can just trigger `cdk deploy` again. 
That way the enclave docker container would be build again which automatically triggers the EC2 instances to be recreated and pull, convert and run the new code as a enclave. 
Please keep in mind that all the PCR registers would change as well. So if you are not running the enclave in `debug` mode you have to update the corresponding PRC0 value in the KMS key policy. 

Does that help? 

Chees

**Comment by KiranMo27** [comment]
Oh okay gotcha.
Thanks a ton, that helps me a lot !

I was just hesitant to run `cdk deploy` again because i was under the impression that running `cdk deploy` again would provision the resources all over again.

**Comment by KiranMo27** [comment]
I am able to test the changes much faster now. Thanks !
