### ISSUE TITLE
Incorrect `cd` command in step 2 of instructions

### ISSUE THREAD

**Issue by ebaizel** [aws-samples/aws-nitro-enclave-blockchain-wallet#20]
In step 2, the user clones and then changes directory to the cloned repo. However, the copy and paste command provided does not work because of an extra `s` character in `enclaves` instead of `enclave`.

Currently:
`git clone https://github.com/aws-samples/aws-nitro-enclave-blockchain-wallet.git && cd aws-nitro-enclaves-blockchain-wallet`

Should be (note in the `cd` command at the end):
`git clone https://github.com/aws-samples/aws-nitro-enclave-blockchain-wallet.git && cd aws-nitro-enclave-blockchain-wallet`

**Comment by dpdornseifer** [comment]
Thx @ebaizel , will fix - will also add the missing `build_kmstool_enclave_cli` step
