### ISSUE TITLE
scalability of the solution

### ISSUE THREAD

**Issue by tharinduLR** [aws-samples/aws-nitro-enclave-blockchain-wallet#22]
Thank you for the proposed solution.

By referencing this solution, I am also building something very similar. But when I did the load testing with a single ec2 instance (c6a.xlarge), I was unable to run 10 requests per second. The successful rate is 3-4 requests per second.

According to your testing, Am I doing something wrong?

I implement a test API in the http server to check the resource consumption of the https://github.com/aws-samples/aws-nitro-enclave-blockchain-wallet/blob/main/application/eth1/enclave/server.py#L14.

For that i ran,  

aws kms decrypt \
    --ciphertext-blob <ciphertext-blob> \
    --key-id <key-id> \
    --encryption-algorithm <algorithm>  \
    --region <region> \
    --output json

as a python subprocess in the http-server as a test api.(we believe this resource consumption is similar to the here:  https://github.com/aws-samples/aws-nitro-enclave-blockchain-wallet/blob/main/application/eth1/enclave/server.py#L14). Then CPU max out at 10 requests per second.

Is there any way to increase the request count per second without adding auto-scaling or using a higher-performance ec2?

**Comment by tharinduLR** [comment]
@dpdornseifer thank you for the response,

As per your suggestion, I have increased the number of outbound workers of vsock proxy to 10. Additionally, I've developed an API utilizing the psutil library to monitor the CPU and memory usage of the enclave. And exposed it to the outside via HTTP server.

When I call the api, which involves a KMS call, with a load test of 3-4 requests per second, the CPU utilization of the enclave reaches approximately 60-70%. However, upon further increasing the request rate, the CPU utilization surpasses 100%.

But, when I use an API that does not involve any KMS call, even with a load test generating 25 requests per second, the CPU utilization remains relatively low, ranging between 20-30%. 

Additionally, it's worth noting that I've implemented multithreading within the enclave to efficiently handle incoming requests.

So it seems that kms call inside the nitro enclave consumes a lot of CPU resources with 3-4 requests per second.

**Comment by dpdornseifer** [comment]
Hi @tharinduLR , 

thanks for the detailed feedback. 
Just wondering, were you able to overcome the 3~4 requests per second limit that you initially faced?

Think we have to differentiate between networking (outbound proxy, vsock routing) and enclave related resource (CPU, memory) constraints looking at the scalability issue here.

**Comment by kannangaranv** [comment]
@dpdornseifer Thank you for your response.
 In our project, we utilized a c6a.x large EC2 instance as the parent EC2 responsible for enclave functionality. This instance is equipped with 4 vCPUs and 8GB of memory. Within our project setup, we allocated 2 vCPUs and 3296 MB of memory for the enclave. Despite increasing the number of outbound workers of the vsock proxy from 4 to 10, we encountered a limitation where the successful rate couldn't surpass 3-4 requests per second.
In light of this challenge, could you please provide recommendations on potential solutions to overcome this limitation?

**Comment by kannangaranv** [comment]
@wgr2017  Thank you for your response.
We accessed the enclave via a lambda function. Initially, there was a constraint on the execution environments utilized in lambda functions, capped at 10. However, upon increasing this limit to 1000, we observed an enhancement in the success rate during load testing, achieving up to 20 requests per second (rps) without encountering any failures.
Subsequently, when load testing the enclave directly, we achieved a higher success rate of approximately 35 rps. Can you help us to clarify why the rps is lower when accessing the enclave through a lambda function?

**Comment by wgr2017** [comment]
@kannangaranv Thanks for your response. I would recommend testing the enclaves without the lambda function, i.e., directly invoking the load balancer url. Consider adding a KMS VPC interface endpoint in your VPC to keep the KMS traffic private, which can also reduce latency. Do let us know your findings with these two changes.
