### ISSUE TITLE
Typo / Bug in in build_kmstool_enclave_cli.sh?

### ISSUE THREAD

**Issue by frankwese** [aws-samples/aws-nitro-enclave-blockchain-wallet#23]
Shouldn't 

https://github.com/aws-samples/aws-nitro-enclave-blockchain-wallet/blob/main/scripts/build_kmstool_enclave_cli.sh#L30
be `sed "s|-f ../../containers/Dockerfile.al2 ../..|-f ../../containers/Dockerfile.al2**_new** ../.. --platform=${TARGET_PLATFORM}|g" build.sh >build.sh_new`

In commit
https://github.com/aws-samples/aws-nitro-enclave-blockchain-wallet/commit/5f6666b21727e2dabeb60f15dac7e62c89582d4e
the `sed` step that re-renamed the Dockerfile was deleted.

**Comment by dpdornseifer** [comment]
Hey @frankwese, 

thanks for reaching out - you are right, the `GOPROXY` statement added to the `Dockerfile.al2_new` file gets ignored due to the naming issue. Will fix.
