### ISSUE TITLE
aws sdk in nitro enclave

### ISSUE THREAD

**Issue by redaready** [aws-samples/aws-nitro-enclave-blockchain-wallet#3]
Hi, thanks for great sample

as for now the enclave python program use "kmstool_enclave_cli" to do the kms decrypt job, it is quit limited and complicated to run.
is it possible to use aws kms python sdk directly(or java sdk)  in the enclave enviroment?

**Comment by dpdornseifer** [comment]
Hi @redaready , 

yes it is possible to use any AWS SDK from inside the enclave. To do so a internal proxy needs to be started: https://nitro-enclaves.workshop.aws/en/my-first-enclave/secure-local-channel.html

These SDKs do not support cryptographic attestation per default. kmstool_enclave_cli is based on the Nitro SDK (https://github.com/aws/aws-nitro-enclaves-sdk-c) and thus can make use of the cryptographic attestation. 

@redaready does that answer your question?

**Comment by redaready** [comment]
thanks david,  that's all what i need
