### ISSUE TITLE
`./scripts/get_pcr0.sh <EC2 instance ID>` returns an empty string

### ISSUE THREAD

**Issue by 0xYao** [aws-samples/aws-nitro-enclave-blockchain-wallet#5]
- A reproducible test case or series of steps
  - After deploying the whole stack using `cdk deploy devNitroWalletEth`, I tried running the command `./scripts/get_pcr0.sh <EC2 instance ID>` to get the unique hash value of the Nitro Enclave, but the command returns an empty string.
- The version of our code being used
  - Commit `1fa0d541af348f49fc6533e05232ac64b9991f93`
- Any modifications you've made relevant to the bug
  - N/A
- Anything unusual about your environment or deployment
  - N/A

# My workaround

I had to connect to the EC2 instance using the session manager and execute the command `sudo nitro-cli describe-eif --eif-path /home/ec2-user/app/server/signing_server.eif`, and retrieve the PCR0 value under the Measurements field, e.g.

<img width="734" alt="image" src="https://user-images.githubusercontent.com/48658585/188289710-d79655ee-af4d-4236-a40e-a9ea68361742.png">

I propose to include this workaround in either `README.md` or the relevant section of the blog post.

**Comment by dpdornseifer** [comment]
@0xYao , 
thanks for sharing this issue. The issue with `./scripts/get_pcr0.sh` indicates that the enclave was not running at the time you executed the command. Did you confirm that the enclave has been started at a later point in time using the `sudo nitro-cli describe-enclaves` command?

**Comment by 0xYao** [comment]
> @0xYao , thanks for sharing this issue. The issue with `./scripts/get_pcr0.sh` indicates that the enclave was not running at the time you executed the command. Did you confirm that the enclave has been started at a later point in time using the `sudo nitro-cli describe-enclaves` command?

No, I didn't run the `sudo nitro-cli describe-enclaves` command. I think it was around 10-20 minutes after the deployment of the stack  when I tried to connect to connect to the EC2 instance using the session manager.

Does it take around 10-20 minutes for the enclave to be up and running?

**Comment by dpdornseifer** [comment]
@0xYao no, the enclave should be available latest one minute after the deployment has been finished. Which region did you deploy the solution to?
