### ISSUE TITLE
Unable to List Nitro-Enclaves or Connect

### ISSUE THREAD

**Issue by ryan-ohare-nydig** [aws-samples/aws-nitro-enclave-blockchain-wallet#7]
* A reproducible test case or series of steps
  * Part 2 of the blog post, setting post setting up the instances in cdk. The nitro-enclaves appear to come up but are in some odd state. `describe-enclaves` returns a null set despite the enclaves are up and running.
  * Evidence:
```
sh-4.2$ sudo su
[root@ip-10-0-195-156 bin]# nitro-cli describe-enclaves
[]
[root@ip-10-0-195-156 bin]# ps -ef | grep nitro-cli
root     13721 13712  0 10:49 ?        00:00:00 /bin/nitro-cli run-enclave --cpu-count 2 --memory 3806 --eif-path /home/ec2-user/app/server/signing_server.eif --enclave-cid 16
root     13730 13721  0 10:49 ?        00:00:00 [nitro-cli] <defunct>
root     13733     1 16 10:49 ?        00:00:09 /bin/nitro-cli run-enclave --cpu-count 2 --memory 3806 --eif-path /home/ec2-user/app/server/signing_server.eif --enclave-cid 16
root     13961 13753  0 10:50 pts/0    00:00:00 grep --color=auto nitro-cli
[root@ip-10-0-195-156 bin]#
```
Additionally the health checks are failing for the target groups. This appears related to the closed issues #4  and  #5.

* The version of our code being used
  * 7f96f2f0a7d2b5598fc474558bb614bccce33894

 * Any modifications you've made relevant to the bug
   * N/A
 * Anything unusual about your environment or deployment
   * Running everything in us-east-2

**Comment by dpdornseifer** [comment]
Thanks for your contribution @ryan-ohare-nydig. Reviewed and added your PR.
